#!/bin/sh

# Author: https://github.com/softwaredownload/openwrt-fanqiang
# Date: 2014-08-22


uci set dropbear.@dropbear[0].GatewayPorts=on

uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'

uci commit dropbear
uci commit system

/etc/init.d/dropbear restart
/etc/init.d/system restart

